// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwlowouzadclyaviazed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3bG93b3V6YWRjbHlhdmlhemVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzY2MjUsImV4cCI6MjA2MTQxMjYyNX0.2XZJcBQjvDqo2aAe8ikqF0gxayNVvZ_i2um3cbawe2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);